### ISSUE TITLE
Provide an arm64 image on Docker Hub

### ISSUE THREAD

**Issue by Tomaszal** [cs3org/wopiserver#109]
Could you possibly provide an arm64 image on Docker Hub? Right now I am able to use this project on an arm64 system, but I need to build it myself, which is less convenient. It also requires a few changes to build successfully due to grpcio limitations. There are 2 options:

1. Add `linux-headers` package before installing the requirements, as it's needed to [build the grpico wheels](https://github.com/grpc/grpc/issues/24722) which are [not available for arm64 alpine/musl systems](https://github.com/grpc/grpc/issues/21283#issuecomment-821026924). Unfortunately, while this works, it takes a very long time to build.
2. Switch to a slim-buster base python image instead of alpine, which has the necessary wheels pre-built already. While the resulting image will be larger, the build time is much smaller.

For a single use (i.e. building manually) the 2nd option makes more sense. However, if add an arm64 image build as part of CI/CD for Docker Hub (not sure how it's set up here) the 1st option is probably better.

**Comment by glpatcern** [comment]
Hi there, could you please elaborate on how you're currently using this project in your system? Do you also use [Reva](https://github.com/cs3org/reva) or do you use local storage?
Currently we do not support arm64, but a priori it is not complex to extend the CI for this build, especially now that it is based on standard GitHub actions.

**Comment by Tomaszal** [comment]
Hi, I'm using wopiserver for OwnCloud Infinite Scale integration setup as shown in this [example docker-compose](https://github.com/owncloud/ocis/blob/master/deployments/examples/ocis_wopi/docker-compose.yml). It does seem to use Reva, although I'm not too sure how it works in general. Everything else in that setup provides arm64 images, the only thing that currently needs to be build manually is wopiserver.

**Comment by glpatcern** [comment]
I see, indeed you're using Reva behind oCIS.

I'd invite you to extend the `release.yml` CI script to build an extra image on top of the 2 existing ones, maybe only on tags (so even if it takes a long time it's not for every single commit). As said arm64 is currently not supported and we don't plan to make and test such build, but I'm happy to review a PR for it.

**Comment by Tomaszal** [comment]
I've submitted the PRs of my attempt, not sure if it's correct as I've never worked with GitHub CI before and wasn't able to test it.

Also, since opening this issue I've actually switched the oCIS host to a x86 host, as the arm64 host I had was not powerful enough to run it well. Hopefully the PRs work well, but if not, perhaps someone else can take over them in the future if they need an arm64 image.

**Comment by micbar** [comment]
hi @Tomaszal 

oCIS already builds ARM compatible docker containers which include Reva.

https://hub.docker.com/layers/owncloud/ocis/2.0/images/sha256-4afac6637e393be506bb11797bac3928496fada21fb49e6adcf4f67ee5590a78?context=explore

**Comment by Tomaszal** [comment]
Hi @micbar, I'm aware that oCIS already has an ARM image and it works great on its own. However, as I understand, an ARM wopiserver image is still needed to integrate OnlyOffice/Collabora with oCIS, as shown in [this example](https://github.com/owncloud/ocis/blob/master/deployments/examples/ocis_wopi/docker-compose.yml).
