### ISSUE TITLE
Option to disable healthcheck logging

### ISSUE THREAD

**Issue by xoxys** [cs3org/wopiserver#123]
With wopiserver v10 a new healthcheck was introduced in https://github.com/cs3org/wopiserver/pull/122 which causes a lot of noise. Can we have an option to disable logging for the healthcheck or move it to the debug level? IMO, creating a log entry for every single *successful* healthcheck call is not very helpful.

**Comment by xoxys** [comment]
Thanks!

**Comment by glpatcern** [comment]
No problem! You're welcome to contribute a patch in such cases ;-)

**Comment by xoxys** [comment]
Happy to do :) This issue was meant to be for discussion as it happens too often that people investigate into a PR which is getting rejected because the maintainers disagree on implementing it.

**Comment by glpatcern** [comment]
Fair enough, though this one is not an architectural change so not much contentious.

As I'm at it, I introduced this health check for the ScienceMesh deployments, as having the wopiserver "up and running" but unable to talk to Reva is basically a broken deployment.
