### ISSUE TITLE
Improper URL concatenation

### ISSUE THREAD

**Issue by DeepDiver1975** [cs3org/wopiserver#150]
https://github.com/cs3org/wopiserver/blob/b4b35d4a84bc4d497190df74d786409836ebe3d0/src/core/wopiutils.py#L181

Instead of string concatenation functions like `urljoin` or `urlunsplit` should be used to construct URLs to prevent double slashes which can lead to issues.

`wopiurl` as well as `wopiproxy` suffer from this issue when setup with a trailing slash.

**Comment by glpatcern** [comment]
Good catch, but rather than introducing `urljoin` that has some interesting side effects if (ever) `wopiurl` also includes a path (e.g. from reverse proxies), I have stripped the trailing slashes when reading the config - see PR. Would that be enough?
