### ISSUE TITLE
Use syslog format for logging

### ISSUE THREAD

**Issue by labkode** [cs3org/wopiserver#29]
The format of the WOPI logs is neither RFC-3164 nor RFC-5424 compliant. Parsing the current logs will require custom regex.
Can we use the stdlib syslog package to log messages in the wopiserver?

**Comment by glpatcern** [comment]
Closing this as we solved the issue in a different way: by enabling fluentd logging for the docker container running the wopiserver.

A separate issue is to JSON-ify the log to be more fluentd-friendly.
