### ISSUE TITLE
Further lint the code

### ISSUE THREAD

**Issue by glpatcern** [cs3org/wopiserver#60]
Having integrated flake8 in the CI, a number of lint suggestions is available and could be implemented quite easily to further improve readability of the code base.

**Comment by osamaahmed17** [comment]
Was fixing this issue, wanted to confirm whether you guys are using "Pylint" to lint the code? https://pypi.org/project/pylint/

**Comment by pascalwengerter** [comment]
You could also take a look at https://github.com/psf/black?

**Comment by glpatcern** [comment]
I know black, but that's a bit extreme, especially when it comes to line length (my personal opinion is that with nowadays screens, 120-130 chars per line are perfectly acceptable and make for _more_ readable code).

Otherwise, the CI uses flake8 as mentioned and it's already a good reference.

**Comment by osamaahmed17** [comment]
@glpatcern, I have made changes to the wopiserver.py but I can't push my branch. It shows "remote: Permission to cs3org/wopiserver.git denied to osamaahmed17." Have you guys added extra security?

**Comment by shreyaansjain06** [comment]
I tried checking it with flake8 

It mainly shows two types of error and this is one of them 

`E501 line too long (106 > 79 characters)`

According to it, line should have almost 79 characters  you are saying 120-130 chars per line 

So am I missing something?

**Comment by osamaahmed17** [comment]
That's great, it's merged. Horray!... We can make this issue resolved. I would have done it but I don't have rights.

**Comment by glpatcern** [comment]
Yes, the number of linting warnings was drastically dropped with the extra changes introduced in the PR.

Yet I will keep this issue open with a very low priority, for whenever we can at least partially address the remaining warnings (did not have time yesterday to also look for those). The current master build shows the following:
```
18    C901 '<function>' is too complex (14)
5     E124 closing bracket does not match visual indentation
5     E302 expected 2 blank lines, found 1
3     E305 expected 2 blank lines after class or function definition, found 1
29    E501 line too long (145 > 130 characters)
4     E741 ambiguous variable name 'l'
77
```

**Comment by glpatcern** [comment]
Closing this as with the latest we have brought the lint warnings to a handful.
