### ISSUE TITLE
Configurable log handler

### ISSUE THREAD

**Issue by xoxys** [cs3org/wopiserver#83]
Instead of a hard-coded file handler for logging, it would be helpful to make it configurable. At least an optional stream handler might make sense in a container environment.

**Comment by glpatcern** [comment]
I can see the advantage in a fully (e.g. helm-based) containerized environment, however so far we have run this service in a hybrid environment, where log files are piped through other non-containerized services as well as "traditionally" rotated.
Of course having both options would be good.
